name: windows
inputs:
  py_version:
    required: true
runs:
  using: composite
  steps:
  - uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
    with:
      miniconda-version: "latest"
      python-version: ${{ inputs.py_version }}
      activate-environment: hydra
  - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
    with:
      distribution: 'microsoft'
      java-version: '21'
